/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import static gerenciapenalti.GerenciaPenalti.inicializaObjetosAtleticoMineiro;
import static gerenciapenalti.GerenciaPenalti.inicializaObjetosCorinthians;
import static gerenciapenalti.GerenciaPenalti.inicializaObjetosCruzeiro;
import static gerenciapenalti.GerenciaPenalti.inicializaObjetosFlamengo;
import static gerenciapenalti.GerenciaPenalti.inicializaObjetosFluminense;
import static gerenciapenalti.GerenciaPenalti.inicializaObjetosSantos;
import gerenciapenalti.Jogador;
import java.util.Random;

/**
 *
 * @author Juliano
 */
public class JFrameMeuTime extends javax.swing.JFrame {

    //nome dos times
    public String nomeTime1;    
    public String nomeTimePC;
    //vetor de jogadores do time que o jogador escolheu
    private Jogador jogadores1[];
    //vetor de jogadores do time gerado para o pc
    private Jogador jogadores2[];
    //contador de controle
    private int contador = 1;
    //vetores de time final para o jogo (1 Goleiro e 5 Batedores)
    private Jogador[] jogadoresJog = new Jogador[6];
    private Jogador[] jogadoresPC = new Jogador[6];

    /**
     * Creates new form JFrameMeuTime
     */
    public JFrameMeuTime(String nomeTime, Jogador jogadores[]) {
        initComponents();
        nomeTime1 = nomeTime;
        jogadores1 = jogadores;
        iniciaTimeComputador();
        jLabelNomeTime.setText(nomeTime);
        jButtonConfirmar.setVisible(false);
        //atribuindo goleiros às primeiras posições
        jogadoresJog[0] = jogadores1[0];
        jogadoresPC[0] = jogadores2[0];
        //inicializando botões
        jButtonJ1.setText(jogadores1[1].getNome());
        jButtonJ2.setText(jogadores1[2].getNome());
        jButtonJ3.setText(jogadores1[3].getNome());
        jButtonJ4.setText(jogadores1[4].getNome());
        jButtonJ5.setText(jogadores1[5].getNome());
        jButtonJ6.setText(jogadores1[6].getNome());
        jButtonJ7.setText(jogadores1[7].getNome());
        jButtonJ8.setText(jogadores1[8].getNome());
        jButtonJ9.setText(jogadores1[9].getNome());
        jButtonJ10.setText(jogadores1[10].getNome());
        jTextAreaExibeJogadores.setText("Nome\tFunção" + "\n");
        jTextAreaExibeJogadores.setText(this.jTextAreaExibeJogadores.getText() + this.jogadores1[0].getNome() + "\tGoleiro\n");

    }

    private JFrameMeuTime() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomeTime = new javax.swing.JLabel();
        jButtonJ1 = new javax.swing.JButton();
        jButtonJ2 = new javax.swing.JButton();
        jButtonJ3 = new javax.swing.JButton();
        jButtonJ4 = new javax.swing.JButton();
        jButtonJ5 = new javax.swing.JButton();
        jButtonJ6 = new javax.swing.JButton();
        jButtonJ7 = new javax.swing.JButton();
        jButtonJ8 = new javax.swing.JButton();
        jButtonJ9 = new javax.swing.JButton();
        jButtonJ10 = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaExibeJogadores = new javax.swing.JTextArea();
        jLabelInstrucao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNomeTime.setText("nomeTime");
        getContentPane().add(jLabelNomeTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 11, -1, -1));

        jButtonJ1.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jButtonJ2.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        jButtonJ3.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonJ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJ3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jButtonJ4.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonJ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJ4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jButtonJ5.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonJ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJ5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jButtonJ6.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonJ6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJ6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        jButtonJ7.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonJ7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJ7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jButtonJ8.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonJ8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJ8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        jButtonJ9.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonJ9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJ9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        jButtonJ10.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonJ10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJ10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJ10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 340, 110, 30));

        jTextAreaExibeJogadores.setEditable(false);
        jTextAreaExibeJogadores.setColumns(20);
        jTextAreaExibeJogadores.setRows(5);
        jScrollPane1.setViewportView(jTextAreaExibeJogadores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 231, 135));

        jLabelInstrucao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInstrucao.setForeground(new java.awt.Color(0, 102, 102));
        jLabelInstrucao.setText("Selecione mais cinco jogadores para formar a sua equipe");
        getContentPane().add(jLabelInstrucao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 310, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 10, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ1ActionPerformed
        // TODO add your handling code here:
        jogadoresJog[contador] = jogadores1[1];
        jogadoresPC[contador] = jogadores2[1];
        contador = contador + 1;
        jTextAreaExibeJogadores.setText(this.jTextAreaExibeJogadores.getText() + this.jogadores1[1].getNome() + "\tBatedor\n");
        if (contador >= 6) {
            finalizaBotao();
        } else {
            jButtonJ1.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonJ1ActionPerformed

    private void jButtonJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ2ActionPerformed
        // TODO add your handling code here:
        jogadoresJog[contador] = jogadores1[2];
        jogadoresPC[contador] = jogadores2[2];
        contador = contador + 1;
        jTextAreaExibeJogadores.setText(this.jTextAreaExibeJogadores.getText() + this.jogadores1[2].getNome() + "\tBatedor\n");
        if (contador >= 6) {
            finalizaBotao();
        } else {
            jButtonJ2.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonJ2ActionPerformed

    private void jButtonJ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ3ActionPerformed
        // TODO add your handling code here:
        jogadoresJog[contador] = jogadores1[3];
        jogadoresPC[contador] = jogadores2[3];
        contador = contador + 1;
        jTextAreaExibeJogadores.setText(this.jTextAreaExibeJogadores.getText() + this.jogadores1[3].getNome() + "\tBatedor\n");
        if (contador >= 6) {
            finalizaBotao();
        } else {
            jButtonJ3.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonJ3ActionPerformed

    private void jButtonJ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ4ActionPerformed
        // TODO add your handling code here:
        jogadoresJog[contador] = jogadores1[4];
        jogadoresPC[contador] = jogadores2[4];
        jTextAreaExibeJogadores.setText(this.jTextAreaExibeJogadores.getText() + this.jogadores1[4].getNome() + "\tBatedor\n");
        contador = contador + 1;
        if (contador >= 6) {
            finalizaBotao();
        } else {
            jButtonJ4.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonJ4ActionPerformed

    private void jButtonJ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ5ActionPerformed
        // TODO add your handling code here:
        jogadoresJog[contador] = jogadores1[5];
        jogadoresPC[contador] = jogadores2[5];
        contador = contador + 1;
        jTextAreaExibeJogadores.setText(this.jTextAreaExibeJogadores.getText() + this.jogadores1[5].getNome() + "\tBatedor\n");
        if (contador >= 6) {
            finalizaBotao();
        } else {
            jButtonJ5.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonJ5ActionPerformed

    private void jButtonJ6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ6ActionPerformed
        // TODO add your handling code here:
        jogadoresJog[contador] = jogadores1[6];
        jogadoresPC[contador] = jogadores2[6];
        contador = contador + 1;
        jTextAreaExibeJogadores.setText(this.jTextAreaExibeJogadores.getText() + this.jogadores1[6].getNome() + "\tBatedor\n");
        if (contador >= 6) {
            finalizaBotao();
        } else {
            jButtonJ6.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonJ6ActionPerformed

    private void jButtonJ7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ7ActionPerformed
        // TODO add your handling code here:
        jogadoresJog[contador] = jogadores1[7];
        jogadoresPC[contador] = jogadores2[7];
        contador = contador + 1;
        jTextAreaExibeJogadores.setText(this.jTextAreaExibeJogadores.getText() + this.jogadores1[7].getNome() + "\tBatedor\n");
        if (contador >= 6) {
            finalizaBotao();
        } else {
            jButtonJ7.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonJ7ActionPerformed

    private void jButtonJ8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ8ActionPerformed
        // TODO add your handling code here:        
        jogadoresJog[contador] = jogadores1[8];
        jogadoresPC[contador] = jogadores2[8];
        contador = contador + 1;
        jTextAreaExibeJogadores.setText(this.jTextAreaExibeJogadores.getText() + this.jogadores1[8].getNome() + "\tBatedor\n");
        if (contador >= 6) {
            finalizaBotao();
        } else {
            jButtonJ8.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonJ8ActionPerformed

    private void jButtonJ9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ9ActionPerformed
        // TODO add your handling code here:
        jogadoresJog[contador] = jogadores1[9];
        jogadoresPC[contador] = jogadores2[9];
        contador = contador + 1;
        jTextAreaExibeJogadores.setText(this.jTextAreaExibeJogadores.getText() + this.jogadores1[9].getNome() + "\tBatedor\n");
        if (contador >= 6) {
            finalizaBotao();
        } else {
            jButtonJ9.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonJ9ActionPerformed

    private void jButtonJ10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJ10ActionPerformed
        // TODO add your handling code here:
        jogadoresJog[contador] = jogadores1[10];
        jogadoresPC[contador] = jogadores2[10];
        contador = contador + 1;
        jTextAreaExibeJogadores.setText(this.jTextAreaExibeJogadores.getText() + this.jogadores1[10].getNome() + "\tBatedor\n");
        if (contador >= 6) {
            finalizaBotao();
        } else {
            jButtonJ10.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonJ10ActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        // TODO add your handling code here:
        JFrameJogo jFrameJogo = new JFrameJogo(jogadoresJog, jogadoresPC);
        this.setVisible(false);
        jFrameJogo.setLocationRelativeTo(null);
        jFrameJogo.setVisible(true);
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMeuTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMeuTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMeuTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMeuTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMeuTime().setVisible(true);
            }
        });
    }

    private void finalizaBotao() {
        jButtonJ1.setEnabled(false);
        jButtonJ2.setEnabled(false);
        jButtonJ3.setEnabled(false);
        jButtonJ4.setEnabled(false);
        jButtonJ5.setEnabled(false);
        jButtonJ6.setEnabled(false);
        jButtonJ7.setEnabled(false);
        jButtonJ8.setEnabled(false);
        jButtonJ9.setEnabled(false);
        jButtonJ10.setEnabled(false);
        jButtonConfirmar.setVisible(true);

    }

    private void iniciaTimeComputador() {
        Random sorteia = new Random();
        int numTime;
        String timePC = null;
        do {
            numTime = sorteia.nextInt(6);
            switch (numTime) {
                case 0:
                    timePC = "Corinthians";
                    break;
                case 1:
                    timePC = "Cruzeiro";
                    break;
                case 2:
                    timePC = "Santos";
                    break;
                case 3:
                    timePC = "Atlético Mineiro";
                    break;
                case 4:
                    timePC = "Flamengo";
                    break;
                case 5:
                    timePC = "Fluminense";
                    break;
            }
        } while (nomeTime1.equals(timePC));
        Jogador jogadorPC[] = new Jogador[11];
        switch (numTime) {
            case 0:
                jogadorPC = inicializaObjetosCorinthians();
                break;
            case 1:
                jogadorPC = inicializaObjetosCruzeiro();
                break;
            case 2:
                jogadorPC = inicializaObjetosSantos();
                break;
            case 3:
                jogadorPC = inicializaObjetosAtleticoMineiro();
                break;
            case 4:
                jogadorPC = inicializaObjetosFlamengo();
                break;
            case 5:
                jogadorPC = inicializaObjetosFluminense();
                break;
        }
        jogadores2 = jogadorPC;

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonJ1;
    private javax.swing.JButton jButtonJ10;
    private javax.swing.JButton jButtonJ2;
    private javax.swing.JButton jButtonJ3;
    private javax.swing.JButton jButtonJ4;
    private javax.swing.JButton jButtonJ5;
    private javax.swing.JButton jButtonJ6;
    private javax.swing.JButton jButtonJ7;
    private javax.swing.JButton jButtonJ8;
    private javax.swing.JButton jButtonJ9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelInstrucao;
    private javax.swing.JLabel jLabelNomeTime;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaExibeJogadores;
    // End of variables declaration//GEN-END:variables
}
