/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

/**
 *
 * @author Juliano
 */
public class JFrameInicial extends javax.swing.JFrame {

    /**
     * Creates new form JFrameInicial
     */
    public JFrameInicial() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1Jogador = new javax.swing.JButton();
        jButtonAjudaJogar = new javax.swing.JButton();
        jLabelBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kick-Katch");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(455, 328));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1Jogador.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1Jogador.setText("Jogar");
        jButton1Jogador.setOpaque(false);
        jButton1Jogador.setPreferredSize(new java.awt.Dimension(100, 30));
        jButton1Jogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1JogadorActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Jogador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 151, -1));

        jButtonAjudaJogar.setText("Ajuda");
        jButtonAjudaJogar.setOpaque(false);
        jButtonAjudaJogar.setPreferredSize(new java.awt.Dimension(100, 30));
        jButtonAjudaJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjudaJogarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAjudaJogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        jLabelBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/12648003_1060116067383855_1461246633_n.jpg"))); // NOI18N
        getContentPane().add(jLabelBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1JogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1JogadorActionPerformed
        // TODO add your handling code here:
        JFrameSelecionaTime jFrameSelecionaTime = new JFrameSelecionaTime();
        this.setVisible(false);
        jFrameSelecionaTime.setLocationRelativeTo(null);
        jFrameSelecionaTime.setVisible(true);
    }//GEN-LAST:event_jButton1JogadorActionPerformed

    private void jButtonAjudaJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjudaJogarActionPerformed
        // TODO add your handling code here:
        JFrameHelp jFrameHelp = new JFrameHelp();
        //this.setVisible(false);
        jFrameHelp.setLocation(50, 190);
        jFrameHelp.setVisible(true);
    }//GEN-LAST:event_jButtonAjudaJogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Jogador;
    private javax.swing.JButton jButtonAjudaJogar;
    private javax.swing.JLabel jLabelBG;
    // End of variables declaration//GEN-END:variables
}
