/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import gerenciapenalti.GerenciaPenalti;
import gerenciapenalti.Jogador;

/**
 *
 * @author Juliano
 */
public class JFrameSelecionaTime extends javax.swing.JFrame {

    /**
     * Creates new form JFrameSelecionaTime
     */
    public JFrameSelecionaTime() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTime = new javax.swing.ButtonGroup();
        jLabelSelecaoTime = new javax.swing.JLabel();
        jButtonVerJogadoresCorinthians = new javax.swing.JButton();
        jButtonVerJogadoresCruzeiro = new javax.swing.JButton();
        jButtonVerJogadoresSantos = new javax.swing.JButton();
        jButtonVerJogadoresAtleticoMineiro = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jButtonFlamengo = new javax.swing.JButton();
        jButtonFluminense = new javax.swing.JButton();
        jLabelInstrucao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabelSelecaoTime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSelecaoTime.setText("Seleção de Time");

        jButtonVerJogadoresCorinthians.setText("Corinthians");
        jButtonVerJogadoresCorinthians.setPreferredSize(new java.awt.Dimension(150, 30));
        jButtonVerJogadoresCorinthians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerJogadoresCorinthiansActionPerformed(evt);
            }
        });

        jButtonVerJogadoresCruzeiro.setText("Cruzeiro");
        jButtonVerJogadoresCruzeiro.setPreferredSize(new java.awt.Dimension(150, 30));
        jButtonVerJogadoresCruzeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerJogadoresCruzeiroActionPerformed(evt);
            }
        });

        jButtonVerJogadoresSantos.setText("Santos");
        jButtonVerJogadoresSantos.setPreferredSize(new java.awt.Dimension(150, 30));
        jButtonVerJogadoresSantos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerJogadoresSantosActionPerformed(evt);
            }
        });

        jButtonVerJogadoresAtleticoMineiro.setText("Atlético Mineiro");
        jButtonVerJogadoresAtleticoMineiro.setPreferredSize(new java.awt.Dimension(150, 30));
        jButtonVerJogadoresAtleticoMineiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerJogadoresAtleticoMineiroActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonFlamengo.setText("Flamengo");
        jButtonFlamengo.setPreferredSize(new java.awt.Dimension(150, 30));
        jButtonFlamengo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlamengoActionPerformed(evt);
            }
        });

        jButtonFluminense.setText("Fluminense");
        jButtonFluminense.setPreferredSize(new java.awt.Dimension(150, 30));
        jButtonFluminense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFluminenseActionPerformed(evt);
            }
        });

        jLabelInstrucao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelInstrucao.setForeground(new java.awt.Color(0, 102, 102));
        jLabelInstrucao.setText("Selecione um dos times abaixo para ver seus jogadores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabelSelecaoTime))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonVerJogadoresCorinthians, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonVerJogadoresAtleticoMineiro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButtonFluminense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonFlamengo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonVerJogadoresSantos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonVerJogadoresCruzeiro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabelInstrucao)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabelSelecaoTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelInstrucao, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonVerJogadoresCorinthians, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVerJogadoresCruzeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVerJogadoresSantos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVerJogadoresAtleticoMineiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButtonFlamengo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFluminense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonVoltar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerJogadoresCorinthiansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerJogadoresCorinthiansActionPerformed
        // TODO add your handling code here:
        Jogador jogadores[] = new Jogador[11];
        jogadores = GerenciaPenalti.inicializaObjetosCorinthians();
        JFrameExibeJogadores jFrameExibeJogadores = new JFrameExibeJogadores("/imagens/319.png", "Corinthians", jogadores);
        this.setVisible(false);
        jFrameExibeJogadores.setLocationRelativeTo(null);
        jFrameExibeJogadores.setVisible(true);
    }//GEN-LAST:event_jButtonVerJogadoresCorinthiansActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        // TODO add your handling code here:
        JFrameInicial jFrameInicial = new JFrameInicial();
        this.setVisible(false);
        jFrameInicial.setLocationRelativeTo(null);
        jFrameInicial.setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonVerJogadoresCruzeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerJogadoresCruzeiroActionPerformed
        // TODO add your handling code here:
        Jogador jogadores[] = new Jogador[11];
        jogadores = GerenciaPenalti.inicializaObjetosCruzeiro();
        JFrameExibeJogadores jFrameExibeJogadores = new JFrameExibeJogadores("/imagens/321.png", "Cruzeiro", jogadores);
        this.setVisible(false);
        jFrameExibeJogadores.setLocationRelativeTo(null);
        jFrameExibeJogadores.setVisible(true);
    }//GEN-LAST:event_jButtonVerJogadoresCruzeiroActionPerformed

    private void jButtonVerJogadoresSantosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerJogadoresSantosActionPerformed
        // TODO add your handling code here:
        Jogador jogadores[] = new Jogador[11];
        jogadores = GerenciaPenalti.inicializaObjetosSantos();
        JFrameExibeJogadores jFrameExibeJogadores = new JFrameExibeJogadores("/imagens/335.png", "Santos", jogadores);
        this.setVisible(false);
        jFrameExibeJogadores.setLocationRelativeTo(null);
        jFrameExibeJogadores.setVisible(true);
    }//GEN-LAST:event_jButtonVerJogadoresSantosActionPerformed

    private void jButtonVerJogadoresAtleticoMineiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerJogadoresAtleticoMineiroActionPerformed
        // TODO add your handling code here:
        Jogador jogadores[] = new Jogador[11];
        jogadores = GerenciaPenalti.inicializaObjetosAtleticoMineiro();
        JFrameExibeJogadores jFrameExibeJogadores = new JFrameExibeJogadores("/imagens/314.png", "Atlético Mineiro", jogadores);
        this.setVisible(false);
        jFrameExibeJogadores.setLocationRelativeTo(null);
        jFrameExibeJogadores.setVisible(true);
    }//GEN-LAST:event_jButtonVerJogadoresAtleticoMineiroActionPerformed

    private void jButtonFlamengoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlamengoActionPerformed
        // TODO add your handling code here:
        Jogador jogadores[] = new Jogador[11];
        jogadores = GerenciaPenalti.inicializaObjetosFlamengo();
        JFrameExibeJogadores jFrameExibeJogadores = new JFrameExibeJogadores("/imagens/322.png", "Flamengo", jogadores);
        this.setVisible(false);
        jFrameExibeJogadores.setLocationRelativeTo(null);
        jFrameExibeJogadores.setVisible(true);
    }//GEN-LAST:event_jButtonFlamengoActionPerformed

    private void jButtonFluminenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFluminenseActionPerformed
        // TODO add your handling code here:
        Jogador jogadores[] = new Jogador[11];
        jogadores = GerenciaPenalti.inicializaObjetosFluminense();
        JFrameExibeJogadores jFrameExibeJogadores = new JFrameExibeJogadores("/imagens/323.png", "Fluminense", jogadores);
        this.setVisible(false);
        jFrameExibeJogadores.setLocationRelativeTo(null);
        jFrameExibeJogadores.setVisible(true);
    }//GEN-LAST:event_jButtonFluminenseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold jButtonConfirmartate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameSelecionaTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameSelecionaTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameSelecionaTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameSelecionaTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameSelecionaTime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTime;
    private javax.swing.JButton jButtonFlamengo;
    private javax.swing.JButton jButtonFluminense;
    private javax.swing.JButton jButtonVerJogadoresAtleticoMineiro;
    private javax.swing.JButton jButtonVerJogadoresCorinthians;
    private javax.swing.JButton jButtonVerJogadoresCruzeiro;
    private javax.swing.JButton jButtonVerJogadoresSantos;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelInstrucao;
    private javax.swing.JLabel jLabelSelecaoTime;
    // End of variables declaration//GEN-END:variables
}
